### ISSUE TITLE
Remote "origin" does not support the Git LFS locking API

### ISSUE THREAD

**Issue by Wsine** [milkey-mouse/git-lfs-s3-proxy#4]
I followed your instructions but came up with a problem. I would like to seek your help. Do you know any with this problem?

```
Remote "origin" does not support the Git LFS locking API. Consider disabling it with:
  $ git config lfs.<unknown>.locksverify false
Uploading LFS objects:   0% (0/1), 0 B | 0 B/s, done.
batch request: missing protocol: "<unknown>"
error: failed to push some refs to 'github.com:Wsine/test.git'
```

**Comment by Wsine** [comment]
I managed to solve the problem by encoding the `<SECRET_ACCESS_KEY>` via https://www.urlencoder.org/.

The key contains `/` characters. Maybe some hints on the Readme file can help to ease the use.

I am keeping the issue open for your review before closing it.

**Comment by Wsine** [comment]
Also, I configured with `git config lfs.locksverify false` to disable the locking.

**Comment by twilligon** [comment]
I'll add that to the README. By the way, what S3 provider were you using?

I think the `locksverify` thing is unrelated; it shows up even on successful pushes/pulls for me. We probably can't support the LFS locking API.

**Comment by Wsine** [comment]
I am using the `Backblaze B2` backend
